const image = {
    emptyFolder: require("./EmptyFolder.png"),
    coloredBackground: require("./coloredBackground.png"),
    coloredLogo: require("./coloredLogo.png"),
    deposit: require("./deposit.png"),
    key: require("./key.png"),
    lock: require("./lock.png"),
    logo: require("./logo.svg"),
    notes: require("./notes.png"),
    send: require("./send.png"),
    wallet: require("./wallet.png"),
    nervosCoin: require("./nervos-coin.png"),
    dollarCoin: require("./dollar-coin.png"),
    euroCoin: require("./euro-coin.png"),
    poundCoin: require("./pound-coin.png"),
    yenCoin: require("./yen-coin.png"),
    yuanCoin: require("./yuan-coin.png"),
    animation: require("./animation.webp"),
};
export { image };
