name: "🐞 Bug Report"
description: "Report a reproducible bug"
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: Thank you for reporting a bug! Your feedback helps us improve. Please complete the form below with as much detail as possible.
    - type: dropdown
      id: os
      attributes:
          label: Operating system
          description: Operating system
          options:
              - Android
              - IOS
      validations:
          required: true
    - type: textarea
      attributes:
          label: Steps to reproduce
          description: Provide a detailed list of steps to reproduce the bug.
          placeholder: "1. 2. 3. 4."
          value: "Bug steps"
      validations:
          required: true
    - type: textarea
      attributes:
          label: Expected behavior
          description: Describe what you expected to happen.
          placeholder: "Expected behavior"
          value: "Expected behavior"
      validations:
          required: true
    - type: textarea
      attributes:
          label: Actual behavior
          description: Describe what actually happened.
          placeholder: "Actual behavior"
          value: "Actual behavior"
      validations:
          required: true
