import {
    abr,
    apys,
    ato,
    aurora,
    babyblackdragon,
    banana,
    bean,
    blackdragon,
    brrr,
    bulla,
    bstn,
    cam,
    celo,
    cheddar,
    chica,
    chill,
    cucumber,
    cusd,
    dai,
    darai,
    dbio,
    deip,
    disc,
    drip,
    eth,
    flx,
    frax,
    four_illia,
    gear,
    gnear,
    gnuff,
    grt,
    gtc,
    hapi,
    hat,
    hijack,
    hot,
    ht,
    intel,
    jump,
    kat,
    linear,
    link,
    lol,
    lonk,
    marmaj,
    mpdao,
    myria,
    ndc,
    neardog,
    nearvember,
    nearvidia,
    nearx,
    neat,
    neko,
    nersig,
    nkok,
    nochill,
    noear,
    nusdo,
    oct,
    oin,
    one_inch,
    one_mil,
    otto,
    paras,
    pnear,
    pumpkg,
    pulse,
    pxt,
    radeonear,
    ref,
    redacted,
    rort,
    sd,
    seat,
    sfrax,
    shitzu,
    sin,
    six_bowen,
    skyward,
    sol,
    stan,
    stnear,
    sweat,
    tao,
    touched,
    tri,
    umint,
    usdc,
    usdce,
    usdt,
    usdte,
    usm,
    usn,
    uto,
    uwon,
    veganfriends,
    wbtc,
    weth,
    wnear,
    wojak,
    woo,
    xref,
    zml,
} from "images";

export const SUPPORTED_TOKENS_IMAGES = {
    "1INCH": one_inch,
    "1MIL": one_mil,
    "4illia": four_illia,
    "6bowen": six_bowen,
    ABR: abr,
    APYS: apys,
    ATO: ato,
    AURORA: aurora,
    BANANA: banana,
    BABYBLACKDRAGON: babyblackdragon,
    BEAN: bean,
    BLACKDRAGON: blackdragon,
    BRRR: brrr,
    BULLA: bulla,
    cam: cam,
    BSTN: bstn,
    CELO: celo,
    Cheddar: cheddar,
    CHICA: chica,
    CHILL: chill,
    CUCUMBER: cucumber,
    cUSD: cusd,
    DAI: dai,
    DARAI: darai,
    DBIO: dbio,
    DEIP: deip,
    DISC: disc,
    DRIP: drip,
    ETH: eth,
    FLX: flx,
    FRAX: frax,
    GEAR: gear,
    GTC: gtc,
    GRT: grt,
    gnear: gnear,
    gnuff: gnuff,
    HAPI: hapi,
    HAT: hat,
    Hijack: hijack,
    HOT: hot,
    HT: ht,
    INTEL: intel,
    JUMP: jump,
    KAT: kat,
    LINEAR: linear,
    LINK: link,
    LOL: lol,
    LONK: lonk,
    MARMAJ: marmaj,
    mpDAO: mpdao,
    MYRIA: myria,
    NDC: ndc,
    NearDOG: neardog,
    NEARvember: nearvember,
    NEARVIDIA: nearvidia,
    NearX: nearx,
    NEAT: neat,
    NEKO: neko,
    NERSIG: nersig,
    nKOK: nkok,
    nUSDO: nusdo,
    noCHILL: nochill,
    NOEAR: noear,
    OCT: oct,
    OIN: oin,
    OTTO: otto,
    PARAS: paras,
    PNEAR: pnear,
    PUMPKG: pumpkg,
    PULSE: pulse,
    PXT: pxt,
    RadeoNEAR: radeonear,
    rort: rort,
    REF: ref,
    Redacted: redacted,
    sFRAX: sfrax,
    SIN: sin,
    SD: sd,
    SEAT: seat,
    SHITZU: shitzu,
    SKYWARD: skyward,
    SOL: sol,
    STAN: stan,
    stnear: stnear,
    SWEAT: sweat,
    TAO: tao,
    TOUCHED: touched,
    TRI: tri,
    UMINT: umint,
    USDC: usdc,
    USDCE: usdce,
    USDT: usdt,
    "USDT.e": usdte,
    USM: usm,
    USN: usn,
    UTO: uto,
    UWON: uwon,
    VEGANFRIENDS: veganfriends,
    WBTC: wbtc,
    WETH: weth,
    wNEAR: wnear,
    wojak: wojak,
    WOO: woo,
    XREF: xref,
    ZML: zml,
};
