const TOKENS = [
    { url: "", symbol: "near" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/USDT.e.png", symbol: "nUSDT" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/USDC.png", symbol: "nUSDC" },
    { url: "", symbol: "nDAI" },
    { url: "", symbol: "nWETH" },
    { url: "", symbol: "n1INCH" },
    { url: "", symbol: "nGRT" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/SKYWARD.png", symbol: "SKYWARD" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/REF.png", symbol: "REF" },
    { url: "", symbol: "BANANA" },
    { url: "", symbol: "nHT" },
    { url: "", symbol: "nGTC" },
    { url: "", symbol: "nUNI" },
    { url: "", symbol: "nWBTC" },
    { url: "", symbol: "nLINK" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/PARAS.png", symbol: "PARAS" },
    { url: "", symbol: "STNEAR" },
    { url: "", symbol: "marmaj" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/PULSE.png", symbol: "PULSE" },
    { url: "", symbol: "ETH" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/AURORA.png", symbol: "AURORA" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/DBIO.png", symbol: "DBIO" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/OCT.png", symbol: "OCT" },
    { url: "", symbol: "HAPI" },
    { url: "", symbol: "META" },
    { url: "", symbol: "nUSDO" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/FLX.png", symbol: "FLX" },
    { url: "", symbol: "PXT" },
    { url: "", symbol: "MYRIA" },
    { url: "", symbol: "CELO" },
    { url: "", symbol: "cUSD" },
    { url: "", symbol: "ABR" },
    { url: "", symbol: "SOL" },
    { url: "", symbol: "UTO" },
    { url: "", symbol: "WOO" },
    { url: "", symbol: "LINEAR" },
    { url: "", symbol: "HBTC" },
    { url: "", symbol: "Cheddar" },
    { url: "", symbol: "PEM" },
    { url: "", symbol: "BRRR" },
    { url: "", symbol: "ATO" },
    { url: "", symbol: "NearX" },
    { url: "", symbol: "SD" },
    { url: "", symbol: "xREF" },
    { url: "https://pub-f313cac3edf54338910a8f6842fd0e9c.r2.dev/sweat.png", symbol: "SWEAT" },
    { url: "", symbol: "NearX" },
    { url: "", symbol: "SEAT" },
    { url: "", symbol: "USN" },
    { url: "", symbol: "USDt" },
    { url: "", symbol: "RFTT" },
];

export function getTokenIconPublic(symbol: string) {
    const token = TOKENS.find((el) => el.symbol === symbol && el.url !== "");
    return token ? token.url : false;
}

export function isTokenIconPublic(symbol: string) {
    return TOKENS.find((el) => el.symbol === symbol && el.url !== "");
}
